### ISSUE TITLE
the img of puzzle 9 is blank

### ISSUE THREAD

**Issue by zhl98** [merlresearch/SMART#1]
Hi，
I have discovered a problem where the image of puzzle 9 is blank.
I don't know if it's a problem with my download or if there's a problem with the dataset itself.
Can you take a look?
![image](https://github.com/merlresearch/SMART/assets/51871747/0a6ba726-3690-480a-89c5-717457431833)

**Comment by anoopcherian** [comment]
This is by design. All puzzles not having an associated puzzle image (i.e., puzzles that are text only) are provided a dummy white image.
